[package]
name = "jet-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
vulkan = ["jet-llama-sys/vulkan"]
vision = ["jet-llama-sys/vision"]

[dependencies]
jet-core.workspace = true
jet-llama-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
tera.workspace = true
tracing.workspace = true

[lints]
workspace = true
