[package]
name = "jet-cli"
build = "build.rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "jet"
path = "src/main.rs"

[features]
default = []
vulkan = ["jet-engine/vulkan"]
cuda = ["jet-engine/cuda"]
metal = ["jet-engine/metal"]
vision = ["jet-engine/vision", "dep:base64"]

[dependencies]
clap.workspace = true
jet-core.workspace = true
jet-engine.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
base64 = { version = "0.22", optional = true }

[lints]
workspace = true
